# Generated by Django 4.1.7 on 2023-05-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_bookmodel_evaluation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmodel",
            name="is_finished",
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="finished_date",
            field=models.DateField(blank=True, default=None),
        ),
    ]
