# Generated by Django 4.1.7 on 2023-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_remove_bookmodel_is_finished_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="finished_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
